"""Add primary key to staff table

Revision ID: 3462f8210ee6
Revises: 1e70d43debc0
Create Date: 2024-12-09 16:52:09.217406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3462f8210ee6'
down_revision: Union[str, None] = '1e70d43debc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
