"""Initial Migration

Revision ID: 880dc59690fa
Revises: 
Create Date: 2024-10-10 15:12:44.054941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '880dc59690fa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.String(), nullable=True),
    sa.Column('rtsp_url', sa.String(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cameras_camera_id'), 'cameras', ['camera_id'], unique=True)
    op.create_index(op.f('ix_cameras_id'), 'cameras', ['id'], unique=False)
    op.create_table('entry_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('person_id', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('age', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entry_logs_camera_id'), 'entry_logs', ['camera_id'], unique=False)
    op.create_index(op.f('ix_entry_logs_id'), 'entry_logs', ['id'], unique=False)
    op.create_index(op.f('ix_entry_logs_person_id'), 'entry_logs', ['person_id'], unique=False)
    op.create_index(op.f('ix_entry_logs_timestamp'), 'entry_logs', ['timestamp'], unique=False)
    op.create_table('exit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('person_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exit_logs_camera_id'), 'exit_logs', ['camera_id'], unique=False)
    op.create_index(op.f('ix_exit_logs_id'), 'exit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_exit_logs_person_id'), 'exit_logs', ['person_id'], unique=False)
    op.create_index(op.f('ix_exit_logs_timestamp'), 'exit_logs', ['timestamp'], unique=False)
    op.create_table('smoking_detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('bbox', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_smoking_detections_camera_id'), 'smoking_detections', ['camera_id'], unique=False)
    op.create_index(op.f('ix_smoking_detections_id'), 'smoking_detections', ['id'], unique=False)
    op.create_index(op.f('ix_smoking_detections_timestamp'), 'smoking_detections', ['timestamp'], unique=False)
    op.create_table('threat_detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('threat_type', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('bbox', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_detections_camera_id'), 'threat_detections', ['camera_id'], unique=False)
    op.create_index(op.f('ix_threat_detections_id'), 'threat_detections', ['id'], unique=False)
    op.create_index(op.f('ix_threat_detections_timestamp'), 'threat_detections', ['timestamp'], unique=False)
    op.create_table('tracking_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.String(), nullable=True),
    sa.Column('person_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('bbox', sa.String(), nullable=True),
    sa.Column('centroid', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracking_logs_camera_id'), 'tracking_logs', ['camera_id'], unique=False)
    op.create_index(op.f('ix_tracking_logs_id'), 'tracking_logs', ['id'], unique=False)
    op.create_index(op.f('ix_tracking_logs_person_id'), 'tracking_logs', ['person_id'], unique=False)
    op.create_index(op.f('ix_tracking_logs_timestamp'), 'tracking_logs', ['timestamp'], unique=False)
    op.create_table('vehicle_detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('vehicle_type', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('bbox', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_detections_camera_id'), 'vehicle_detections', ['camera_id'], unique=False)
    op.create_index(op.f('ix_vehicle_detections_id'), 'vehicle_detections', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_detections_timestamp'), 'vehicle_detections', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_detections_timestamp'), table_name='vehicle_detections')
    op.drop_index(op.f('ix_vehicle_detections_id'), table_name='vehicle_detections')
    op.drop_index(op.f('ix_vehicle_detections_camera_id'), table_name='vehicle_detections')
    op.drop_table('vehicle_detections')
    op.drop_index(op.f('ix_tracking_logs_timestamp'), table_name='tracking_logs')
    op.drop_index(op.f('ix_tracking_logs_person_id'), table_name='tracking_logs')
    op.drop_index(op.f('ix_tracking_logs_id'), table_name='tracking_logs')
    op.drop_index(op.f('ix_tracking_logs_camera_id'), table_name='tracking_logs')
    op.drop_table('tracking_logs')
    op.drop_index(op.f('ix_threat_detections_timestamp'), table_name='threat_detections')
    op.drop_index(op.f('ix_threat_detections_id'), table_name='threat_detections')
    op.drop_index(op.f('ix_threat_detections_camera_id'), table_name='threat_detections')
    op.drop_table('threat_detections')
    op.drop_index(op.f('ix_smoking_detections_timestamp'), table_name='smoking_detections')
    op.drop_index(op.f('ix_smoking_detections_id'), table_name='smoking_detections')
    op.drop_index(op.f('ix_smoking_detections_camera_id'), table_name='smoking_detections')
    op.drop_table('smoking_detections')
    op.drop_index(op.f('ix_exit_logs_timestamp'), table_name='exit_logs')
    op.drop_index(op.f('ix_exit_logs_person_id'), table_name='exit_logs')
    op.drop_index(op.f('ix_exit_logs_id'), table_name='exit_logs')
    op.drop_index(op.f('ix_exit_logs_camera_id'), table_name='exit_logs')
    op.drop_table('exit_logs')
    op.drop_index(op.f('ix_entry_logs_timestamp'), table_name='entry_logs')
    op.drop_index(op.f('ix_entry_logs_person_id'), table_name='entry_logs')
    op.drop_index(op.f('ix_entry_logs_id'), table_name='entry_logs')
    op.drop_index(op.f('ix_entry_logs_camera_id'), table_name='entry_logs')
    op.drop_table('entry_logs')
    op.drop_index(op.f('ix_cameras_id'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_camera_id'), table_name='cameras')
    op.drop_table('cameras')
    # ### end Alembic commands ###
