"""Add business_id to zone

Revision ID: bb32b88230e1
Revises: fc3c1f8f2199
Create Date: 2025-01-01 17:18:54.503163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb32b88230e1'
down_revision: Union[str, None] = 'fc3c1f8f2199'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
