"""Added test case

Revision ID: bcb6b2158c83
Revises: 434a39251053
Create Date: 2025-01-02 17:23:58.528513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcb6b2158c83'
down_revision: Union[str, None] = '434a39251053'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('is_local_test', sa.Boolean(), nullable=True))
    op.add_column('businesses', sa.Column('is_prod_test', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'is_prod_test')
    op.drop_column('businesses', 'is_local_test')
    # ### end Alembic commands ###
