"""Added store Id

Revision ID: cfea632de4b5
Revises: 702ebc60bec6
Create Date: 2025-01-03 22:24:52.839667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfea632de4b5'
down_revision: Union[str, None] = '702ebc60bec6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('store_id', sa.String(), nullable=True))
    op.add_column('zones', sa.Column('store_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zones', 'store_id')
    op.drop_column('cameras', 'store_id')
    # ### end Alembic commands ###
